{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeFamilies #-}

{- |
Module      : DataFrame.Typed.Record
License     : MIT

Bridge a Haskell record type to a typed dataframe schema. Instances are
typically generated by the @deriveSchemaFromType@ Template Haskell splice
(see "DataFrame.Typed.TH"), but can be written by hand as well, or
plugged into the @Generic@-derived defaults from "DataFrame.Typed.Generic".
-}
module DataFrame.Typed.Record (
    -- * Class
    HasSchema (..),

    -- * Untyped helpers
    fromRecords,
    toRecords,

    -- * Typed helpers
    fromRecordsTyped,
    toRecordsTyped,

    -- * Helpers used by generated code
    requireColumn,
) where

import Data.Kind (Type)
import qualified Data.Text as T
import qualified Data.Vector as VB

import qualified DataFrame.Internal.Column as C
import qualified DataFrame.Internal.DataFrame as D
import DataFrame.Operations.Core (fromNamedColumns)
import DataFrame.Typed.Types (TypedDataFrame (..))

{- | Bridge a Haskell record type @a@ to a typed-dataframe schema.

The schema is exposed as an associated type family 'Schema' so that
instances can pick it up from a 'GHC.Generics.Rep' computation (see
'DataFrame.Typed.Generic.SchemaOf') or from an explicit list emitted by
'DataFrame.Typed.TH.deriveSchemaFromType'.

@toColumns@ explodes a list of records into a list of named columns.
@fromColumns@ reconstructs the records from a 'D.DataFrame', returning
@Left err@ if a column is missing or has the wrong type.
-}
class HasSchema a where
    type Schema a :: [Type]
    toColumns :: [a] -> [(T.Text, C.Column)]
    fromColumns :: D.DataFrame -> Either T.Text [a]

{- | Build an untyped 'D.DataFrame' from a list of records.

@
data Order = Order { orderId :: Int64, region :: Text, amount :: Double }
\$(deriveSchemaFromType ''Order)

xs :: [Order]
xs = [Order 1 "us" 10.0, Order 2 "eu" 20.0]

df :: DataFrame
df = fromRecords xs
@
-}
fromRecords :: (HasSchema a) => [a] -> D.DataFrame
fromRecords = fromNamedColumns . toColumns

{- | Parse a list of records out of an untyped 'D.DataFrame'.

Returns @Left err@ on schema mismatch (missing column, wrong type).
-}
toRecords :: (HasSchema a) => D.DataFrame -> Either T.Text [a]
toRecords = fromColumns

-- | Like 'fromRecords' but returns a 'TypedDataFrame' tagged with the schema.
fromRecordsTyped :: forall a. (HasSchema a) => [a] -> TypedDataFrame (Schema a)
fromRecordsTyped = TDF . fromRecords

-- | Like 'toRecords' but accepts a 'TypedDataFrame'.
toRecordsTyped ::
    forall a. (HasSchema a) => TypedDataFrame (Schema a) -> Either T.Text [a]
toRecordsTyped (TDF df) = fromColumns df

{- | Extract a column as a boxed vector by name, returning a 'T.Text' error
on missing column or type mismatch.

Used by code generated by 'DataFrame.Typed.TH.deriveSchemaFromType'.
-}
requireColumn ::
    forall a.
    (C.Columnable a) => T.Text -> D.DataFrame -> Either T.Text (VB.Vector a)
requireColumn name df = case D.getColumn name df of
    Nothing ->
        Left $ "Column '" <> name <> "' not found in DataFrame"
    Just col -> case C.toVector col of
        Right v -> Right v
        Left e ->
            Left $
                "Column '" <> name <> "': " <> T.pack (show e)
